id:        CBR-SEC-GL-GITLAB_CICD_JOB_TOKEN
title:     "Identified a GitLab CI/CD Job Token, potential access to projects and some APIs on behalf of a user "
severity:  high
languages: ['generic']
cwe:       ['CWE-798']
source:    gitleaks/gitlab-cicd-job-token
message: |
  Identified a GitLab CI/CD Job Token, potential access to projects and some APIs on behalf of a user while the CI job is running.
  
  Remediation: Remove the secret, rotate it immediately, and
  store it in a secret manager or environment variable.
regex: |
  glcbt-[0-9a-zA-Z]{1,5}_[0-9a-zA-Z_-]{20}
