id:        CBR-DOCK-REMOVE_PACKAGE_LISTS
title:     "Remove Package Lists"
severity:  high
languages: ['docker']
source:    semgrep/remove-package-lists
message: |
  The package lists were not deleted after running 'apt-get update', which increases the size of the image. Remove the package lists by appending '&& rm -rf /var/lib/apt/lists/*' at the end of apt-get command chain.
pattern: |
  RUN apt-get update ...
