id:        CBR-DOCK-PREFER_COPY_OVER_ADD
title:     "Prefer Copy Over Add"
severity:  medium
languages: ['docker']
source:    semgrep/prefer-copy-over-add
message: |
  The ADD command will accept and include files from a URL and automatically extract archives. This potentially exposes the container to a man-in-the-middle attack or other attacks if a malicious actor can tamper with the source archive. Since ADD can have this and other unexpected side effects, the use of the more explicit COPY command is preferred.
pattern: |
  ADD $FROM $TO
  
