id:        CBR-DOCK-MULTIPLE_ENTRYPOINT_INSTRUCTIO
title:     "Multiple Entrypoint Instructions"
severity:  critical
languages: ['docker']
source:    semgrep/multiple-entrypoint-instructions
message: |
  Multiple ENTRYPOINT instructions were found. Only the last one will take effect.
pattern: |
  ENTRYPOINT ...
  ...
  $ENTRYPOINT_INSTR
  
