id:        CBR-DOCK-MISSING_USER_ENTRYPOINT
title:     "Missing User Entrypoint"
severity:  critical
languages: ['docker']
cwe:       ['CWE-269']
source:    semgrep/missing-user-entrypoint
message: |
  By not specifying a USER, a program in the container may run as 'root'. This is a security hazard. If an attacker can control a process running as root, they may have control over the container. Ensure that the last USER in a Dockerfile is a USER other than 'root'.
pattern: |
  ENTRYPOINT $...VARS
  
fix: |
  USER non-root
  ENTRYPOINT $...VARS
  
