id:        CBR-PYTH-AVOID_HARDCODED_CONFIG_SECRET_
title:     "Avoid Hardcoded Config Secret Key"
severity:  critical
languages: ['python']
cwe:       ['CWE-489']
source:    semgrep/avoid_hardcoded_config_SECRET_KEY
message: |
  Hardcoded variable `SECRET_KEY` detected. Use environment variables or config files instead
pattern: |
  $M.update(SECRET_KEY="=~/.*/")
