id:        CBR-TERR-AWS_EC2_LAUNCH_CONFIGURATION_E
title:     "Aws Ec2 Launch Configuration Ebs Block Device Unencrypted"
severity:  high
languages: ['terraform']
cwe:       ['CWE-311']
source:    semgrep/aws-ec2-launch-configuration-ebs-block-device-unencrypted
message: |
  The AWS launch configuration EBS block device is unencrypted. The block device could be read if compromised. Block devices should be encrypted to ensure sensitive data is held securely at rest.
pattern: |
  ebs_block_device {
    ...
  }
  
